-- INITAL DATA
----- COUNTRIES
-- SELECT NEXTVAL(COUNTRIES_SEQ) FROM DUAL;
INSERT INTO COUNTRIES (COUNTRY_ID, NAME, LANGUAGE, CURRENCY) VALUES (COUNTRIES_SEQ.NEXTVAL, 'Poland', 'polish', 'PLN');
INSERT INTO COUNTRIES (COUNTRY_ID, NAME, LANGUAGE, CURRENCY) VALUES (COUNTRIES_SEQ.NEXTVAL, 'Germany', 'german', 'EUR');
INSERT INTO COUNTRIES (COUNTRY_ID, NAME, LANGUAGE, CURRENCY) VALUES (COUNTRIES_SEQ.NEXTVAL, 'France', 'french', 'EUR');
INSERT INTO COUNTRIES (COUNTRY_ID, NAME, LANGUAGE, CURRENCY) VALUES (COUNTRIES_SEQ.NEXTVAL, 'Italy', 'italian', 'EUR');
INSERT INTO COUNTRIES (COUNTRY_ID, NAME, LANGUAGE, CURRENCY) VALUES (COUNTRIES_SEQ.NEXTVAL, 'Spain', 'spanish', 'EUR');

-- ALTER SEQUENCE COUNTRIES_SEQ START WITH 11;

------ CITIES
-- SELECT NEXT VALUE FOR CITIES_SEQ FROM CITIES;
INSERT INTO CITIES (CITY_ID, NAME, POPULATION, CITY_SIZE, COUNTRY_ID) VALUES (CITIES_SEQ.NEXTVAL, 'Warsaw', 1.86, 517 , 1);
INSERT INTO CITIES (CITY_ID, NAME, POPULATION, CITY_SIZE, COUNTRY_ID) VALUES (CITIES_SEQ.NEXTVAL, 'Cracow', 0.80, 326, 1);
INSERT INTO CITIES (CITY_ID, NAME, POPULATION, CITY_SIZE, COUNTRY_ID) VALUES (CITIES_SEQ.NEXTVAL, 'Lodz', 0.69, 293, 1);
INSERT INTO CITIES (CITY_ID, NAME, POPULATION, CITY_SIZE, COUNTRY_ID) VALUES (CITIES_SEQ.NEXTVAL, 'Wroclaw', 0.64, 292, 1);
INSERT INTO CITIES (CITY_ID, NAME, POPULATION, CITY_SIZE, COUNTRY_ID) VALUES (CITIES_SEQ.NEXTVAL, 'Gdansk', 0.48, 262, 1);

INSERT INTO CITIES (CITY_ID, NAME, POPULATION, CITY_SIZE, COUNTRY_ID) VALUES (CITIES_SEQ.NEXTVAL, 'Berlin', 3.7, 891, 2);
INSERT INTO CITIES (CITY_ID, NAME, POPULATION, CITY_SIZE, COUNTRY_ID) VALUES (CITIES_SEQ.NEXTVAL, 'Hamburg', 1.9, 755, 2);
INSERT INTO CITIES (CITY_ID, NAME, POPULATION, CITY_SIZE, COUNTRY_ID) VALUES (CITIES_SEQ.NEXTVAL, 'Munich', 1.6, 310, 2);

INSERT INTO CITIES (CITY_ID, NAME, POPULATION, CITY_SIZE, COUNTRY_ID) VALUES (CITIES_SEQ.NEXTVAL, 'Paris', 2.1, 105, 3);
INSERT INTO CITIES (CITY_ID, NAME, POPULATION, CITY_SIZE, COUNTRY_ID) VALUES (CITIES_SEQ.NEXTVAL, 'Marseille', 0.87, 204, 3);
INSERT INTO CITIES (CITY_ID, NAME, POPULATION, CITY_SIZE, COUNTRY_ID) VALUES (CITIES_SEQ.NEXTVAL, 'Lyon', 0.52, 47, 3);

INSERT INTO CITIES (CITY_ID, NAME, POPULATION, CITY_SIZE, COUNTRY_ID) VALUES (CITIES_SEQ.NEXTVAL, 'Rome', 2.9, 1285, 4);
INSERT INTO CITIES (CITY_ID, NAME, POPULATION, CITY_SIZE, COUNTRY_ID) VALUES (CITIES_SEQ.NEXTVAL, 'Milan', 1.4, 181, 4);
INSERT INTO CITIES (CITY_ID, NAME, POPULATION, CITY_SIZE, COUNTRY_ID) VALUES (CITIES_SEQ.NEXTVAL, 'Naples', 0.97, 119, 4);

INSERT INTO CITIES (CITY_ID, NAME, POPULATION, CITY_SIZE, COUNTRY_ID) VALUES (CITIES_SEQ.NEXTVAL, 'Madrid', 3.3, 604, 5);
INSERT INTO CITIES (CITY_ID, NAME, POPULATION, CITY_SIZE, COUNTRY_ID) VALUES (CITIES_SEQ.NEXTVAL, 'Barcelona', 1.6, 101, 5);
INSERT INTO CITIES (CITY_ID, NAME, POPULATION, CITY_SIZE, COUNTRY_ID) VALUES (CITIES_SEQ.NEXTVAL, 'Valencia', 0.8, 134, 5);

------ ADRESSES
INSERT INTO ADDRESSES (ADDRESS_ID, STREET, POSTAL_CODE, CITY_ID) VALUES (ADDRESSES_SEQ.NEXTVAL, 'Mini 5', '01-123', 1);
INSERT INTO ADDRESSES (ADDRESS_ID, STREET, POSTAL_CODE, CITY_ID) VALUES (ADDRESSES_SEQ.NEXTVAL, 'Epic 20', '03-456', 1);
INSERT INTO ADDRESSES (ADDRESS_ID, STREET, POSTAL_CODE, CITY_ID) VALUES (ADDRESSES_SEQ.NEXTVAL, 'Christmas street 3', '01-651', 3);
INSERT INTO ADDRESSES (ADDRESS_ID, STREET, POSTAL_CODE, CITY_ID) VALUES (ADDRESSES_SEQ.NEXTVAL, 'Christmas street 4', '01-652', 3);
INSERT INTO ADDRESSES (ADDRESS_ID, STREET, POSTAL_CODE, CITY_ID) VALUES (ADDRESSES_SEQ.NEXTVAL, 'Magical street 77', '07-777', 9);
INSERT INTO ADDRESSES (ADDRESS_ID, STREET, POSTAL_CODE, CITY_ID) VALUES (ADDRESSES_SEQ.NEXTVAL, 'Bagshot Row 1', '05-989', 8);
INSERT INTO ADDRESSES (ADDRESS_ID, STREET, POSTAL_CODE, CITY_ID) VALUES (ADDRESSES_SEQ.NEXTVAL, 'Bagshot Row 3', '05-991', 8);

------- USERS
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD_HASH) VALUES (USERS_SEQ.NEXTVAL, 'Jan', 'Kowalski');
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD_HASH) VALUES (USERS_SEQ.NEXTVAL, 'w', '1');

------ COTTAGES
INSERT INTO COTTAGES (COTTAGE_ID, NAME, ADDRESS_ID, SIZE_M2, BATHROOMS_NUMBER, ROOMS_NUMBER, MAX_PEOPLE_NUM, MIN_PRICE_PER_DAY, OWNER_ID)
    VALUES (COTTAGES_SEQ.NEXTVAL, 'Micro Cottage', 1, 23, 1, 2, 1, 10.89, 1);
INSERT INTO COTTAGES (COTTAGE_ID, NAME, ADDRESS_ID, SIZE_M2, BATHROOMS_NUMBER, ROOMS_NUMBER, MAX_PEOPLE_NUM, MIN_PRICE_PER_DAY, OWNER_ID)
    VALUES (COTTAGES_SEQ.NEXTVAL, 'The Grand Villa', 2, 600, 100, 50, 100, 149.99, 1);
INSERT INTO COTTAGES (COTTAGE_ID, NAME, ADDRESS_ID, SIZE_M2, BATHROOMS_NUMBER, ROOMS_NUMBER, MAX_PEOPLE_NUM, MIN_PRICE_PER_DAY, OWNER_ID)
    VALUES (COTTAGES_SEQ.NEXTVAL,  'Merry Cottage', 3, 45, 1, 5, 3, 25.89, 1);
INSERT INTO COTTAGES (COTTAGE_ID, NAME, ADDRESS_ID, SIZE_M2, BATHROOMS_NUMBER, ROOMS_NUMBER, MAX_PEOPLE_NUM, MIN_PRICE_PER_DAY, OWNER_ID)
    VALUES (COTTAGES_SEQ.NEXTVAL, 'Merry House', 4, 68, 3, 7, 6, 44.89, 1);
INSERT INTO COTTAGES (COTTAGE_ID, NAME, ADDRESS_ID, SIZE_M2, BATHROOMS_NUMBER, ROOMS_NUMBER, MAX_PEOPLE_NUM, MIN_PRICE_PER_DAY, OWNER_ID)
    VALUES (COTTAGES_SEQ.NEXTVAL, 'Elfish Home', 5, 80, 6, 10, 8, 49.99, 2);
INSERT INTO COTTAGES (COTTAGE_ID, NAME, ADDRESS_ID, SIZE_M2, BATHROOMS_NUMBER, ROOMS_NUMBER, MAX_PEOPLE_NUM, MIN_PRICE_PER_DAY, OWNER_ID)
    VALUES (COTTAGES_SEQ.NEXTVAL, 'Hobbit Hole', 6, 56, 2, 4, 2, 17.89, 2);
INSERT INTO COTTAGES (COTTAGE_ID, NAME, ADDRESS_ID, SIZE_M2, BATHROOMS_NUMBER, ROOMS_NUMBER, MAX_PEOPLE_NUM, MIN_PRICE_PER_DAY, OWNER_ID)
    VALUES (COTTAGES_SEQ.NEXTVAL, 'Baggins Hill', 7, 136, 4, 12, 8, 129.99, 2);

------ REVIEWS
INSERT INTO REVIEWS (REVIEW_ID, COTTAGE_ID, AUTHOR_ID, TEXT, DATE_POSTED, GRADE)
    VALUES (REVIEWS_SEQ.NEXTVAL, 2, 1, 'great view, comfy beds. I recommend it to everyone.', TO_DATE('2024-12-10','YYYY-MM-DD'), 5);
INSERT INTO REVIEWS (REVIEW_ID, COTTAGE_ID, AUTHOR_ID, TEXT, DATE_POSTED, GRADE)
    VALUES (REVIEWS_SEQ.NEXTVAL, 2, 1, 'fantastic place', TO_DATE('2024-08-22','YYYY-MM-DD'), 5);
INSERT INTO REVIEWS (REVIEW_ID, COTTAGE_ID, AUTHOR_ID, TEXT, DATE_POSTED, GRADE)
    VALUES (REVIEWS_SEQ.NEXTVAL, 2, 1, 'a bit high price, but definitely worth it', TO_DATE('2023-07-15','YYYY-MM-DD'), 3);
INSERT INTO REVIEWS (REVIEW_ID, COTTAGE_ID, AUTHOR_ID, TEXT, DATE_POSTED, GRADE)
    VALUES (REVIEWS_SEQ.NEXTVAL, 2, 1, 'frogs were very loud. They were making a lot of noise EVERY NIGHT!! Neither me nor my kids could sleep at all! Awful vacation. I did not rest even a little bit becouse of these frogs.', TO_DATE('2020-04-01','YYYY-MM-DD'), 1);
INSERT INTO REVIEWS (REVIEW_ID, COTTAGE_ID, AUTHOR_ID, TEXT, DATE_POSTED, GRADE)
    VALUES (REVIEWS_SEQ.NEXTVAL, 1, 1, 'nice and cozy', TO_DATE('2024-08-11','YYYY-MM-DD'), 5);
INSERT INTO REVIEWS (REVIEW_ID, COTTAGE_ID, AUTHOR_ID, TEXT, DATE_POSTED, GRADE)
    VALUES (REVIEWS_SEQ.NEXTVAL,  1, 1, 'amazing cottage, a bit small but really great', TO_DATE('2024-09-16','YYYY-MM-DD'), 4);


