-- INITAL DATA
----- COUNTRIES
SELECT NEXT VALUE FOR COUNTRIES_SEQ;
INSERT INTO COUNTRIES
    (COUNTRY_ID, NAME, LANGUAGE, CURRENCY)
VALUES
    (1, 'Poland', 'polish', 'zl');

------ CITIES
SELECT NEXT VALUE FOR CITIES_SEQ;
INSERT INTO CITIES
    (CITY_ID, NAME, POPULATION, SIZE, COUNTRY_ID)
VALUES
    (1, 'Warsaw', 100000, 250000, 1);

------ ADRESSES
SELECT NEXT VALUE FOR ADDRESSES_SEQ;
INSERT INTO ADDRESSES
    (ADDRESS_ID, STREET, POSTAL_CODE, CITY_ID)
VALUES
    (1, 'Mini 5', '01-123', 1);

SELECT NEXT VALUE FOR ADDRESSES_SEQ;
INSERT INTO ADDRESSES
    (ADDRESS_ID, STREET, POSTAL_CODE, CITY_ID)
VALUES
    (2, 'Epic 20', '03-456', 1);

------- USERS
SELECT NEXT VALUE FOR USERS_SEQ;
INSERT INTO USERS
    (USER_ID, USERNAME, PASSWORD_HASH)
VALUES
    (5, 'Jan', '$2a$10$P/Hif9oy3dNEcp5sIa5yieq0L1iLxs41DlQ5wEIsp0hCGrufX2.GC');

SELECT NEXT VALUE FOR USERS_SEQ;
INSERT INTO USERS
    (USER_ID, USERNAME, PASSWORD_HASH)
VALUES
    (2, 'w', '1');

------ COTTAGES
SELECT NEXT VALUE FOR COTTAGES_SEQ;
INSERT INTO COTTAGES
    (COTTAGE_ID, NAME, ADDRESS_ID, SIZE_M2, BATHROOMS_NUMBER, MAX_PEOPLE_NUM, ROOMS_NUMBER, MIN_PRICE_PER_DAY, OWNER_ID)
VALUES
    (1, 'Micro Cottage', 1, 23, 1, 1, 2, 10.89, 5);

SELECT NEXT VALUE FOR COTTAGES_SEQ;
INSERT INTO COTTAGES
    (COTTAGE_ID, NAME, ADDRESS_ID, SIZE_M2, BATHROOMS_NUMBER, MAX_PEOPLE_NUM, ROOMS_NUMBER, MIN_PRICE_PER_DAY, OWNER_ID)
VALUES
    (2, 'The Grand Villa', 2, 600, 100, 50, 100, 49.99, 5);