-- SET DB_CLOSE_DELAY -1;
-- CREATE USER IF NOT EXISTS "SA" SALT '4e3a3bcded2dc398' HASH '7f28392927350f5068f027dd266c7dadfa696ec41edc3925cd41241a3a7f2a2d' ADMIN;
CREATE SEQUENCE "COTTAGE_SEQ" START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE "LOGIN_SEQ" START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE "REQUEST_SEQ" START WITH 1 INCREMENT BY 50;

CREATE TABLE "COTTAGE"(
    "BATHROOMS_NUMBER" INTEGER NOT NULL,
    "MAX_PEOPLE_NUM" INTEGER NOT NULL,
    "OWNER_ID" INTEGER NOT NULL,
    "PRICE" INTEGER NOT NULL,
    "ROOMS_NUMBER" INTEGER NOT NULL,
    "SIZE" INTEGER NOT NULL,
    "ID" BIGINT NOT NULL,
    "ADDRESS" CHARACTER VARYING(255) NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE "LOGIN"(
    "ID" INTEGER NOT NULL,
    "PASSWORD" CHARACTER VARYING(255) NOT NULL,
    "USERNAME" CHARACTER VARYING(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE "REQUEST"(
    "COTTAGE_ID" BIGINT NOT NULL,
    "ID" BIGINT NOT NULL,
    "RECIPIENT_ID" BIGINT NOT NULL,
    "SUBMITTER_ID" BIGINT NOT NULL,
    PRIMARY KEY (id)
);
ALTER TABLE "REQUEST" ADD CONSTRAINT "FK_REQUEST_COTTAGE" FOREIGN KEY("COTTAGE_ID") REFERENCES "COTTAGE"("ID") NOCHECK;
