-- SET DB_CLOSE_DELAY -1;
-- CREATE USER IF NOT EXISTS SA SALT '4E3A3BCDED2DC398' HASH '7F28392927350F5068F027DD266C7DADFA696EC41EDC3925CD41241A3A7F2A2D' ADMIN;
DROP SEQUENCE COUNTRIES_SEQ;
DROP SEQUENCE CITIES_SEQ;
DROP SEQUENCE ADDRESSES_SEQ;
DROP SEQUENCE USERS_SEQ;

DROP SEQUENCE COTTAGES_SEQ;
DROP SEQUENCE FACILITIES_SEQ;
DROP SEQUENCE EQUIPMENTS_SEQ;
DROP SEQUENCE RESTRICTIONS_SEQ;

DROP SEQUENCE REVIEWS_SEQ;
DROP SEQUENCE REQUESTS_SEQ;
DROP SEQUENCE REQUEST_APPROVALS_SEQ;

CREATE SEQUENCE COUNTRIES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CITIES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ADDRESSES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE COTTAGES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FACILITIES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE EQUIPMENTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RESTRICTIONS_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE REVIEWS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE REQUESTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE REQUEST_APPROVALS_SEQ START WITH 1 INCREMENT BY 1;

DROP TABLE COUNTRIES CASCADE CONSTRAINTS;
DROP TABLE CITIES CASCADE CONSTRAINTS;
DROP TABLE ADDRESSES CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;

DROP TABLE COTTAGES CASCADE CONSTRAINTS;
DROP TABLE FACILITIES CASCADE CONSTRAINTS;
DROP TABLE COTTAGES_FACILITIES CASCADE CONSTRAINTS;
DROP TABLE EQUIPMENTS CASCADE CONSTRAINTS;
DROP TABLE COTTAGES_EQUIPMENTS CASCADE CONSTRAINTS;
DROP TABLE RESTRICTIONS CASCADE CONSTRAINTS;
DROP TABLE COTTAGES_RESTRICTIONS CASCADE CONSTRAINTS;

DROP TABLE REQUESTS CASCADE CONSTRAINTS;
DROP TABLE REQUEST_APPROVALS CASCADE CONSTRAINTS;
DROP TABLE REVIEWS CASCADE CONSTRAINTS;

CREATE TABLE COUNTRIES(
  COUNTRY_ID NUMBER (8) NOT NULL,
  NAME VARCHAR2 (40) NOT NULL,
  LANGUAGE VARCHAR2(50),
  CURRENCY VARCHAR2(10),
  PRIMARY KEY (COUNTRY_ID)
 );

CREATE TABLE CITIES(
  CITY_ID NUMBER (8) NOT NULL,
  NAME VARCHAR2 (40) NOT NULL ,
  POPULATION DECIMAL(7, 2),
  CITY_SIZE DECIMAL(7, 2),
  COUNTRY_ID NUMBER (8) NOT NULL REFERENCES COUNTRIES(COUNTRY_ID),
  PRIMARY KEY (CITY_ID)
 );

-- ALTER TABLE CITIES
--     ADD CONSTRAINT FK_COUNTRY FOREIGN KEY (COUNTRY_ID)
--     REFERENCES COUNTRIES(COUNTRY_ID);

 CREATE TABLE ADDRESSES(
  ADDRESS_ID NUMBER (8) NOT NULL,
  STREET VARCHAR2 (40) NOT NULL ,
  POSTAL_CODE VARCHAR2 (40 ) NOT NULL ,
  CITY_ID NUMBER (8) NOT NULL REFERENCES CITIES (CITY_ID),
  PRIMARY KEY (ADDRESS_ID)
 );

CREATE TABLE USERS(
    USER_ID NUMBER (8) NOT NULL,
    NAME VARCHAR2 (80),
    SURNAME VARCHAR2 (80),
    EMAIL VARCHAR2 (255),
    USERNAME VARCHAR2(100) NOT NULL,
    PASSWORD_HASH VARCHAR2(100) NOT NULL,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE COTTAGES(
    COTTAGE_ID NUMBER (8) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    SIZE_M2 DECIMAL(7, 2) NOT NULL,
    ADDRESS_ID NUMBER (8) NOT NULL CONSTRAINT ADDR_COTTAGE_FK REFERENCES ADDRESSES (ADDRESS_ID),
    BATHROOMS_NUMBER INTEGER NOT NULL,
    MAX_PEOPLE_NUM INTEGER NOT NULL,
    MIN_PRICE_PER_DAY DECIMAL(7, 2) NOT NULL,
    ROOMS_NUMBER INTEGER NOT NULL,
    OWNER_ID NUMBER (8) NOT NULL CONSTRAINT USER_COTTAGE_FK REFERENCES USERS (USER_ID),
    PRIMARY KEY (COTTAGE_ID)
);

CREATE TABLE FACILITIES(
    FACILITY_ID NUMBER (8) NOT NULL,
    NAME VARCHAR2(40) NOT NULL,
    DESCRIPTION VARCHAR2(100),
    PRIMARY KEY (FACILITY_ID)
);

CREATE TABLE COTTAGES_FACILITIES(
    COTTAGE_ID NUMBER (8) CONSTRAINT COTTAGE_FACILITY_FK REFERENCES COTTAGES (COTTAGE_ID),
    FACILITY_ID NUMBER (8) CONSTRAINT FACILITY_FK REFERENCES FACILITIES (FACILITY_ID),
    PRIMARY KEY (COTTAGE_ID, FACILITY_ID)
);

CREATE TABLE EQUIPMENTS(
    EQUIPMENT_ID NUMBER (8) NOT NULL,
    NAME VARCHAR2(40) NOT NULL,
    DESCRIPTION VARCHAR2(100),
    PRIMARY KEY (EQUIPMENT_ID)
);

CREATE TABLE COTTAGES_EQUIPMENTS(
    COTTAGE_ID NUMBER (8) CONSTRAINT COTTAGE_EQUIPMENT_FK REFERENCES COTTAGES (COTTAGE_ID),
    EQUIPMENT_ID NUMBER (8) CONSTRAINT EQUIPMENT_FK REFERENCES EQUIPMENTS (EQUIPMENT_ID),
    PRIMARY KEY (COTTAGE_ID, EQUIPMENT_ID)
);

CREATE TABLE RESTRICTIONS(
    RESTRICTION_ID NUMBER (8) NOT NULL,
    NAME VARCHAR2(40) NOT NULL,
    DESCRIPTION VARCHAR2(100),
    PRIMARY KEY (RESTRICTION_ID)
);

CREATE TABLE COTTAGES_RESTRICTIONS(
    COTTAGE_ID NUMBER (8)  CONSTRAINT COTTAGE_RESTRICTION_FK REFERENCES COTTAGES (COTTAGE_ID),
    RESTRICTION_ID NUMBER (8) CONSTRAINT RESTRICTION_FK REFERENCES RESTRICTIONS (RESTRICTION_ID),
    PRIMARY KEY (COTTAGE_ID, RESTRICTION_ID)
);


CREATE TABLE REQUESTS(
    REQUEST_ID NUMBER (8) NOT NULL,
    COTTAGE_ID NUMBER (8) NOT NULL CONSTRAINT REQUEST_COTTAGE_FK REFERENCES COTTAGES (COTTAGE_ID) ON DELETE CASCADE,
    CHECKIN_DATE DATE NOT NULL,
    CHECKOUT_DATE DATE NOT NULL,
    TOTAL_PRICE DECIMAL(7, 2) NOT NULL,
    CUSTOMER_ID NUMBER (8) NOT NULL CONSTRAINT REQUEST_CUSTOMER_FK REFERENCES USERS (USER_ID),
    PRIMARY KEY (REQUEST_ID)
);

CREATE TABLE REQUEST_APPROVALS (
  REQUEST_APPROVAL_ID NUMBER (8) NOT NULL,
  DATE_CREATED DATE NOT NULL,
  IS_APPROVED NUMBER (1) NOT NULL,
  REQUEST_ID NUMBER (8) NOT NULL CONSTRAINT REQ_APPROVAL_REQ_FK REFERENCES REQUESTS (REQUEST_ID) ON DELETE CASCADE,
  PRIMARY KEY (REQUEST_APPROVAL_ID)
);

CREATE TABLE REVIEWS(
    REVIEW_ID NUMBER (8) NOT NULL,
    COTTAGE_ID NUMBER (8) NOT NULL CONSTRAINT REVIEW_COTTAGE_FK REFERENCES COTTAGES (COTTAGE_ID) ON DELETE CASCADE,
    AUTHOR_ID NUMBER (8) NOT NULL CONSTRAINT AUTHOR_COTTAGE_FK REFERENCES USERS (USER_ID),
    TEXT VARCHAR2(1020),
    DATE_POSTED DATE NOT NULL,
    GRADE NUMBER (8) NOT NULL,
    PRIMARY KEY (REVIEW_ID)
);

